version: "3.4"

services:
  database:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=hearthbreaker
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
    volumes:
      - ./var/db:/var/lib/postgresql/data:rw
